@echo off
title SOVEREIGN COMMANDER 🦅
echo [1/2] Starting Apache...
cd /d "C:\Apache24\bin"
start httpd.exe -k start
echo [2/2] Starting Brain Core (Python)...
cd /d "C:\Apache24\htdocs"
start /min python brain.py
echo.
echo ✅ ALL SYSTEMS GO.
echo Opening Dashboard...
start http://localhost/DASHBOARD.html
pause
